OBJS-$(CONFIG_AFIR_FILTER)                   += riscv/af_afir_init.o
RVV-OBJS-$(CONFIG_AFIR_FILTER)               += riscv/af_afir_rvv.o
OBJS-$(CONFIG_BLACKDETECT_FILTER) += riscv/vf_blackdetect_init.o
RVV-OBJS-$(CONFIG_BLACKDETECT_FILTER) += riscv/vf_blackdetect_rvv.o

SHLIBOBJS += riscv/cpu_common.o

OBJS-$(CONFIG_OVERLAY_FILTER)                  += riscv/vf_overlay_init.o
RVV-OBJS-$(CONFIG_OVERLAY_FILTER)              += riscv/vf_overlay_rvv.o

OBJS-$(CONFIG_YADIF_FILTER)   += riscv/vf_yadif_init.o
RVV-OBJS-$(CONFIG_YADIF_FILTER) += riscv/vf_yadif_rvv.o
